name = "jetvision-agent"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Account and routing
account_id = "485f44eabd68fe8c5301c12472a02612"

# Environment variables (non-secret)
[vars]
NODE_ENV = "production"

# KV Namespaces for session storage
[[kv_namespaces]]
binding = "KV"
id = "jetvision_kv"

# Development settings
[dev]
port = 3000
local_protocol = "http"

# Environment-specific settings
[env.production]
name = "jetvision-agent"

[env.production.vars]
NODE_ENV = "production"

# Build configuration
[build]
command = "npx @cloudflare/next-on-pages"

# Functions directory
[site]
bucket = ".vercel/output/static"

[[build.upload]]
format = "service-worker"