name: JetVision Platform Test Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run tests daily at 2 AM UTC
    - cron: '0 2 * * *'

env:
  NODE_VERSION: '18.x'
  BUN_VERSION: '1.2.21'
  APOLLO_API_KEY: ${{ secrets.APOLLO_API_KEY }}
  AVAINODE_API_KEY: ${{ secrets.AVAINODE_API_KEY }}
  
jobs:
  # Static Analysis and Linting
  lint-and-format:
    name: Lint and Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Install dependencies - JetVision Agent
        run: bun install --frozen-lockfile
        
      - name: Lint JetVision Agent
        run: bun run lint
        
      - name: Format Check JetVision Agent
        run: bun run format:check

  # Unit Tests
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Install dependencies - JetVision Agent
        run: bun install --frozen-lockfile
        
      - name: Run Unit Tests - JetVision Agent
        working-directory: ./apps/web
        run: bun run test:ci
          
      - name: Upload Coverage - JetVision Agent
        uses: codecov/codecov-action@v3
        with:
          file: ./apps/web/coverage/lcov.info
          flags: jetvision-agent
          name: jetvision-agent-coverage

  # Integration Tests
  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Install dependencies - JetVision Agent
        run: bun install --frozen-lockfile
        
      - name: Build JetVision Agent
        run: bun run build
        
      - name: Start JetVision Agent in background
        working-directory: ./apps/web
        run: |
          npm start &
          echo $! > webapp.pid
          sleep 10
          
      - name: Wait for Web App to be ready
        run: timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'
        
      - name: Stop services
        if: always()
        run: |
          [ -f apps/web/webapp.pid ] && kill $(cat apps/web/webapp.pid) || true

  # End-to-End Tests
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    needs: integration-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Install dependencies and build JetVision Agent
        run: |
          bun install --frozen-lockfile
          bun run build
          
      - name: Run E2E Tests - JetVision Agent
        working-directory: ./apps/web
        run: bun run test:e2e

  # Performance Tests
  performance-tests:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: integration-tests
    if: github.event_name == 'schedule' || contains(github.event.head_commit.message, '[perf-test]')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Install and build JetVision Agent
        run: |
          bun install --frozen-lockfile
          bun run build

  # Security Tests
  security-tests:
    name: Security Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          
      - name: Run Bun audit - JetVision Agent
        run: bun audit

  # Deployment Tests
  deployment-tests:
    name: Deployment Tests
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}
          
      - name: Test Build - JetVision Agent
        run: |
          bun install --frozen-lockfile
          bun run build
          
      - name: Validate package.json files
        run: |
          node -e "
            const fs = require('fs');
            const path = require('path');
            
            const packages = [
              './package.json',
              './apps/web/package.json'
            ];
            
            packages.forEach(pkg => {
              if (fs.existsSync(pkg)) {
                const content = JSON.parse(fs.readFileSync(pkg, 'utf8'));
                console.log(\`✓ \${pkg} is valid JSON\`);
                
                if (!content.name || !content.version) {
                  throw new Error(\`Invalid package.json: \${pkg}\`);
                }
              }
            });
            
            console.log('✅ All package.json files are valid');
          "

  # Notification
  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [lint-and-format, unit-tests, integration-tests, e2e-tests]
    if: always()
    steps:
      - name: Notify Success
        if: needs.unit-tests.result == 'success' && needs.integration-tests.result == 'success'
        run: |
          echo "✅ All tests passed successfully!"
          echo "- Linting: ${{ needs.lint-and-format.result }}"
          echo "- Unit Tests: ${{ needs.unit-tests.result }}"
          echo "- Integration Tests: ${{ needs.integration-tests.result }}"
          echo "- E2E Tests: ${{ needs.e2e-tests.result }}"
          
      - name: Notify Failure
        if: needs.unit-tests.result == 'failure' || needs.integration-tests.result == 'failure' || needs.e2e-tests.result == 'failure'
        run: |
          echo "❌ Some tests failed:"
          echo "- Linting: ${{ needs.lint-and-format.result }}"
          echo "- Unit Tests: ${{ needs.unit-tests.result }}"
          echo "- Integration Tests: ${{ needs.integration-tests.result }}"
          echo "- E2E Tests: ${{ needs.e2e-tests.result }}"
          exit 1